### PR TITLE
update micromamba Dockerfile for Singularity runtime

### PR DESCRIPTION
**Pull request by marcodelapierre**
This update makes sure that `_activate_current_env.sh` is also executed when running containers with Singularity.

One caveat: at this stage I have only updated the Dockefile and nothing else. Are other updates required? e.g. docs or unit tests?

### CODE REVIEW

**Comment by maresb** [comment]
Thanks @marcodelapierre for the contribution!

This will cause the scripts we copy into `/usr/local/bin/` to be owned by `root`. This could potentially break workflows that involve `mambauser` altering these scripts. Perhaps `mambauser` shouldn't be altering these scripts in any case?

I don't know anything about Singularity, so the extra file could potentially surprise/confuse people like me who expect this to look exactly like the base image. I don't have any particular opinion, but perhaps something in terms of a comment in the `Dockerfile` and/or a one-line `README` file inside the image could alleviate this?

**Comment by wholtz** [comment]
Hello @marcodelapierre. Thank you for taking the time to contribute a PR.

It is unclear to me exactly what shortcoming of the current image you are trying to overcome. It would be very helpful if you could provide an `apptainer` command that fails with the current image but works with your PR.  This same command would be good to include as a  test.  If you like, I can convert the commands into tests as it will take some effort to update our test environment to have `apptainer` available.

Currently, when I use the image generated by your PR I get the following:

```shell
$ apptainer run  docker-daemon:micromamba:pr381
INFO:    Using cached SIF image
eval: 81:43: parameter expansion requires a literal

'micromamba' is running as a subprocess and can't modify the parent shell.
Thus you must initialize your shell before using activate and deactivate.

To initialize the current  shell, run:
    $ eval "$(micromamba shell hook --shell )"
and then activate or deactivate with:
    $ micromamba activate
To automatically initialize all future () shells, run:
    $ micromamba shell init --shell  --root-prefix=~/micromamba
If your shell was already initialized, reinitialize your shell with:
    $ micromamba shell reinit --shell 
Otherwise, this may be an issue. In the meantime you can run commands. See:
    $ micromamba run --help

Supported shells are {bash, zsh, csh, xonsh, cmd.exe, powershell, fish}.
critical libmamba Shell not initialized
Apptainer>
```

That is coming from `/.singularity.d/env/91-environment.sh` line 8 which results in the execution of `/bin/micromamba shell hook --shell=bash` .  Within the `micromamba` shell init script, the message `eval: 81:43: parameter expansion requires a literal` appears to be referencing  the body of this function:

```bash
  _umamba_zsh_completions()
  {
    COMPREPLY=($(__mamba_exe completer "${(@s: :)${(@s: :)COMP_LINE}:1}"))
  }
```

The image does not use the `zsh` shell, so I'm confused why this is getting executed at all, but I haven't dug into this in detail.

I looked up [the documentation on `/.singularity.d/`](https://apptainer.org/docs/user/main/environment_and_metadata.html#singularity-d-directory) and I am some what concerned about these two statements:
* "You should not manually modify files under /.singularity.d, from your definition file during builds, or directly within your container image."
* "Whenever possible, avoid modifying or creating environment files manually to prevent potential issues building & running containers with future versions of Apptainer."

I believe these two statements are expressing a strong preference for using `apptainer build ...` to generate the content that resides under `/.singularity.d/`, which isn't an option for us, unless we start building and distributing a SIF image. But it does sound like this part of `apptainer` isn't the most stable and may be a moving target.

One last note, if this PR does end up moving forward, it will need to go into the `dev` branch per [our development policies](https://micromamba-docker.readthedocs.io/en/latest/development.html).

**Comment by marcodelapierre** [comment]
Longer story (some extra comments):
- I refactored my PR because I could not find an effective way to overcome the issue pointed out by @wholtz  (thank you! :-)  )
- @maresb the scripts in`/usr/local/bin/` are owned by root any way, which does not pose an issue
- @wholtz as regards the use of `/.singularity.d/env/91-environment.sh`, you are right, my first implementation was not super best practice, as it does work now but it is not guaranteed to work in the future; to comply with best practices, replacing that path with `$SINGULARITY_ENVIRONMENT` should be enough, see [Environment from a Definition File](https://docs.sylabs.io/guides/latest/user-guide/environment_and_metadata.html#environment-from-a-definition-file)

**Comment by maresb** [comment]
IMO this is a bit of a dirty hack which enables most things to work when the environment is not properly activated, but could mask more serious problems and prevents deactivation of the environment. You can do this if you want, but I don't think we should do it by default. (This makes me more of a purist than ContinuumIO which I acknowledge is a bit weird.)

**Comment by maresb** [comment]
Thanks a lot @marcodelapierre for taking the time to articulate your case. Your request is genuinely noted. We took a design decision some time ago on this, and time will tell whether or not this decision was correct.

This isn't something I'd completely rule out in the future, and @wholtz may even decide overrule me here. But for stability's sake we shouldn't change this on a whim.

**Comment by wholtz** [comment]
I am strongly opposed to setting the `$PATH` to include the `bin` directory for the `base` environment as this breaks using multiple environments in a single image.

While I noted the `apptainer` documentation  warns about placing files under `/.singularity.d/`, I believe this warning is targeted at people who are making SIF images and not us. I am not opposed to populating files under `/.singularity.d/` if it enabled the desired behavior.

Do our documented workarounds for `apptainer shell` not work for you?

```
apptainer exec --shell --shell /usr/local/bin/_apptainer_shell.sh mambaorg/micromamba:1.5.1
```
or
```
APPTAINER_SHELL=/usr/local/bin/_apptainer_shell.sh apptainer exec mambaorg/micromamba:s 1.5.1
```
Please note that until 2 days ago, the `/usr/local/bin/_apptainer_shell.sh` file had been accidentally left out of the image.

We have slowly been improving our support of `apptainer` and I hope to be able to continue to make improvements for `apptainer` usage.

**Comment by marcodelapierre** [comment]
Hi @wholtz , thank you for sharing your perspective and tips. 

Yes, the workarounds do work, but as a personal posture when working with containers, I am always on the look for robust setups that minimise intervention on the command line, and instead achieve the required setup through appropriate image setup. 

I am aware though that it is not always possible to achieve this goal with reasonably simple setups. In this specific case, I did get swamped with the subtleties of how apptainer/singularity implement the shell behaviour in containers; I have investigated several attempts behind this PR, but haven't found a working one yet.

**Pull request closed without merging**
