### PR TITLE
Fix workflow

### PR DESCRIPTION
**Pull request by maresb**
https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/3

### CODE REVIEW

**Comment by maresb** [comment]
Closes #90 for real

**Comment by wholtz** [comment]
@maresb I'm not confident this is the solution but we can give it a try. You'll also need to replace `pull_request` with `push` in the `check_version` step. And the `on:` block of `test.yaml` should be updated to match.

**Comment by maresb** [comment]
> You'll also need to replace `pull_request` with `push` in the `check_version` step.

Yes, thanks!!!

> And the `on:` block of `test.yaml` should be updated to match.

Are you sure? I think we do want to test on pull request.

**Comment by wholtz** [comment]
The last merge into main did  not trigger the `push_latest` workflow....

**Pull request merged**
