### PR TITLE
Fix activation for interactive use in subshells

### PR DESCRIPTION
**Pull request by adriendelsalle**
Description
---

Fix activation for interactive use in sub-shells:
- init `bash` shell and activate completion for nicer interactive use
- activate `$ENV_NAME` from `.bashrc`

### CODE REVIEW

**Comment by wholtz** [comment]
Hi @adriendelsalle -- thanks for the PR.  I'm trying to figure out under what conditions you were loosing the activation of the environment? I'd like to add a test to ensure that we maintain this functionality....

**Comment by adriendelsalle** [comment]
Hi @wholtz
If you keep the default entrypoint/command, the current behavior is to run the shell hook to get the shell function and then activate the correct environment before running `bash`.
This opens a sub-shell where the previously defined shell functions are not defined and the env is not activated (e.g. `micromamba activate` doesn't work).

By adding those extra lines it initializes the (bash) sub-shell, defines completion function, and activates the env.

**Comment by wholtz** [comment]
I see that within the bash shell resulting from the `exec "$@"` in `entrypoint.sh`, the `micromamba` shell functions are not loaded. I agree that should be fixed. But `/bin/micromamba info` indicates that the base env is active. Additionally, if start another sub-shell, `/bin/micromamba info` still shows the base env is active. What am I doing differently from you?

```
$ docker run -it --rm mambaorg/micromamba:0.18.1 /bin/bash
micromamba@9ca1a1745b04:/tmp$ declare -F
micromamba@9ca1a1745b04:/tmp$ micromamba info

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/


            environment : base (active)
           env location : /opt/conda
      user config files : /home/micromamba/.mambarc
 populated config files : 
       libmamba version : 0.18.1
     micromamba version : 0.18.1
       virtual packages : __unix=0=0
                          __linux=5.10.47=0
                          __glibc=2.31=0
                          __archspec=1=x86_64
               channels : 
       base environment : /opt/conda
               platform : linux-64
micromamba@9ca1a1745b04:/tmp$ /bin/bash
micromamba@9ca1a1745b04:/tmp$ micromamba info

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/


            environment : base (active)
           env location : /opt/conda
      user config files : /home/micromamba/.mambarc
 populated config files : 
       libmamba version : 0.18.1
     micromamba version : 0.18.1
       virtual packages : __unix=0=0
                          __linux=5.10.47=0
                          __glibc=2.31=0
                          __archspec=1=x86_64
               channels : 
       base environment : /opt/conda
               platform : linux-64
micromamba@9ca1a1745b04:/tmp$
```

**Comment by adriendelsalle** [comment]
Thanks for your answer!
It's just that the sub-shell inherits environment variables so `MAMBA_ROOT_PREFIX` and `CONDA_PREFIX` are set to the same value from the sh activation [here](https://github.com/mamba-org/micromamba-docker/blob/ab4563ae4e56e74b3b4e6925e93b5c36e3ff152a/entrypoint.sh#L13), making the sub-shell properly activated for the base env but missing the shell function and the PS1 correctly set.

**Comment by maresb** [comment]
Thanks @wholtz for linking this issue with https://github.com/mamba-org/micromamba-docker/issues/57. There I observe that if `mamba.sh` exists, then it gets used as the shell init script. However, it doesn't define the `micromamba()` bash function, so you can't activate with `micromamba activate xyz`.

**Comment by wholtz** [comment]
@adriendelsalle - I took your general ideas and made a new PR where moved most of the `.bashrc` setup into Dockerfile `RUN` commands. See PR #58. I believe this resolves the issues you raised in this PR. Please let me know if you think this is incorrect.  My PR did not resolve the linked issue #57.

**Comment by adriendelsalle** [comment]
@wholtz thanks!
Is it for performance consideration you preferred to move that code in the Dockerfile?

**Comment by wholtz** [comment]
Oh shoot. Sorry @adriendelsalle , I wrote comment explaining why I moved `.bashrc` into the Dockerfile but must have closed my browser tab before posting the comment.

Through my work, I see some uncommon corner cases. I frequently use https://github.com/NERSC/shifter to run containers. By default shifter mounts the host home directories into the container. Therefore, writing to `~/.bashrc` in the entrypoint ends up changing the user's  `~/.bashrc` on the host file system.  Because of this, I want to avoid writing anything to `$HOME` in the entrypoint script, but writing to `$HOME` in the Dockerfile with `RUN ...` commands is fine.

Of course this means that users who run this container with shifter will still have problems with the micromamba function being available in sub-shells. I wanted to get the fix for the more general case commited and this narrow use of shifter can be improved upon later.

I should probably put this information into the Development section of the README.md....

**Pull request closed without merging**
