### PR TITLE
fix: improved check_version.py error handling

### PR DESCRIPTION
**Pull request by wholtz**
invalid semver strings now convert to 0.0.1

### CODE REVIEW

**Comment by maresb** [comment]
Hey, I'm just wondering about the context on this one. What leads to invalid semver strings, and why would we want to convert them to 0.0.1 instead of hard failing?

**Comment by wholtz** [comment]
The `2.0.0alpha1` release was causing the `check_version.py` to die and a pull request was not being auto generated for `1.5.6`.  Since I don't control the version strings, I needed some way to ignore invalid versions. I'm certainly open to better ways....

**Comment by wholtz** [comment]
Another approach would be to put in a blacklist of known bad version strings that we allow (return 0.0.1 or something similar) and we die on new bad version strings. That probably would be a bit better.

**Comment by wholtz** [comment]
Another approach would be to put in a blacklist of known bad version strings that we allow (return 0.0.1 or something similar) and we die on new bad version strings. That probably would be a bit better.

**Comment by maresb** [comment]
I use the `packaging` package for version parsing. It seems to be more robust:

```python
from packaging.version import Version

Version("2.0.0alpha1")
# <Version('2.0.0a1')>
```

Would that fit into your workflow?

**Comment by wholtz** [comment]
Changed to `packaging.version` in #400

**Pull request merged**
