### PR TITLE
More robust activation in _entrypoint.sh

### PR DESCRIPTION
**Pull request by maresb**
Works around #57, https://github.com/mamba-org/mamba/issues/1322

Does activation in a new script `_activate_current_env.sh`

Moves the scripts from `/bin/` to `/usr/local/bin/`

Changes shebang in `_entrypoint.sh`

### CODE REVIEW

**Comment by wholtz** [comment]
Hey @maresb -- this is looking good. If this resolves #57, then could you add a test that fails before this PR but will pass with the PR? Ideally the test would not involve installing mamba, as that is a tad slow. Perhaps doing something similar to the echo to mamaba.sh example that you had in the #57 discussion. Adding the test will ensure we don't regress on with some later change. Thanks! And let me know if you have questions about locally running the test suite or creating tests.

**Comment by maresb** [comment]
Thanks! Unfortunately I don't have time right now. Hopefully I can get to it this weekend.

**Comment by maresb** [comment]
I added the test. I'm going to do an rebase and squash some stuff. Also, something looks screwy with my fork, so I might need to rebase even more seriously...

**Comment by maresb** [comment]
> then could you add a test that fails before this PR but will pass with the PR?

I restructured my PR into two commits, exactly how you requested ("Add failing test" + "Fix failing test").

**Comment by maresb** [comment]
xref workaround for https://github.com/mamba-org/mamba/issues/1322

**Pull request merged**
